// <auto-generated />
using System;
using CrashCourseWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrashCourseWeb.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230914145229_seeded")]
    partial class seeded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CrashCourseWeb.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("474dff0a-9189-41ef-bf66-782e44d02f6a"),
                            Email = "favourmbagwu@gmail.com",
                            FirstName = "Favour",
                            LastName = "Mbagwu",
                            Password = "niceGurl2001",
                            Tel = "09033226688",
                            Username = "mbah34"
                        },
                        new
                        {
                            Id = new Guid("f0281b36-a65f-4f94-a7dd-e417170664bf"),
                            Email = "klaus@gmail.com",
                            FirstName = "Okorie",
                            LastName = "Kelechi",
                            Password = "klaus44",
                            Tel = "09033233772",
                            Username = "modrid68"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
